# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'RNAuthExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNAuthExample
  pod 'AppAuth', '>= 0.91'

  target 'RNAuthExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
